// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWst1vDn3aLv4YApwnonms6Z3I26K4yIw',
    appId: '1:141426942084:web:f93fc687053f7c4b0222d1',
    messagingSenderId: '141426942084',
    projectId: 'project1-bdc1b',
    authDomain: 'project1-bdc1b.firebaseapp.com',
    storageBucket: 'project1-bdc1b.appspot.com',
    measurementId: 'G-0N56GFQCD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1Sxtx41BJdP7LPPRPVTUpStdcy6_vvjg',
    appId: '1:141426942084:android:5271d3df3204d6bb0222d1',
    messagingSenderId: '141426942084',
    projectId: 'project1-bdc1b',
    storageBucket: 'project1-bdc1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9JUs2KbqFkUW135QKhVG3NZ1R_pECoYg',
    appId: '1:141426942084:ios:272e24b9547f3d020222d1',
    messagingSenderId: '141426942084',
    projectId: 'project1-bdc1b',
    storageBucket: 'project1-bdc1b.appspot.com',
    androidClientId: '141426942084-f93nq61la7pl8el16323gf5uudv592hd.apps.googleusercontent.com',
    iosClientId: '141426942084-gftj2ml88d12rk7mlj6t1altv3la3a6j.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitpalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9JUs2KbqFkUW135QKhVG3NZ1R_pECoYg',
    appId: '1:141426942084:ios:9fb7d4f3cc3a7c310222d1',
    messagingSenderId: '141426942084',
    projectId: 'project1-bdc1b',
    storageBucket: 'project1-bdc1b.appspot.com',
    androidClientId: '141426942084-f93nq61la7pl8el16323gf5uudv592hd.apps.googleusercontent.com',
    iosClientId: '141426942084-acu11v5bf6d3ubvkrn8alvu3solbls7o.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitpalProject.RunnerTests',
  );
}
